// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLQF5Vq-L-dhaa9MQ4pzKjIjUe0P0etAE',
    appId: '1:304475250698:web:e0185e07e12ebf5c63bff3',
    messagingSenderId: '304475250698',
    projectId: 'ottdemo-af1b0',
    authDomain: 'ottdemo-af1b0.firebaseapp.com',
    databaseURL: 'https://ottdemo-af1b0-default-rtdb.firebaseio.com',
    storageBucket: 'ottdemo-af1b0.appspot.com',
    measurementId: 'G-KBVSYEP553',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ML0UQ92L9emQV5YGzFI6Kxo7ay-Wb3Q',
    appId: '1:304475250698:android:f9bb1a913055144e63bff3',
    messagingSenderId: '304475250698',
    projectId: 'ottdemo-af1b0',
    databaseURL: 'https://ottdemo-af1b0-default-rtdb.firebaseio.com',
    storageBucket: 'ottdemo-af1b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3y-NsA_8A-eP3D__LEwD_SEAujs9c0mc',
    appId: '1:304475250698:ios:b14b35aaf9eb27a863bff3',
    messagingSenderId: '304475250698',
    projectId: 'ottdemo-af1b0',
    databaseURL: 'https://ottdemo-af1b0-default-rtdb.firebaseio.com',
    storageBucket: 'ottdemo-af1b0.appspot.com',
    iosClientId: '304475250698-cv2d9r16gt2mmm99c4ksa376h8sms53r.apps.googleusercontent.com',
    iosBundleId: 'com.ottDemo',
  );
}
